CREATE TABLE IF NOT EXISTS dist_lock (
  lock_key VARCHAR(255) NOT NULL,
  owner VARCHAR(128) NOT NULL DEFAULT '',
  expire_time BIGINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (lock_key)
);

CREATE TABLE IF NOT EXISTS dist_lock_fence (
  lock_key VARCHAR(255) NOT NULL,
  fencing_token BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (lock_key)
);
